// <auto-generated />
using System;
using BitByByte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BitByByte.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20231116043621_init db")]
    partial class initdb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BitByByte.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "151d1261-2505-44e4-90fe-3957d31e9a2e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "581b68d2-3545-46e6-b198-23f3e8277a7f",
                            Email = "admin@beanscene.com",
                            EmailConfirmed = true,
                            FirstName = "Test",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BEANSCENE.COM",
                            NormalizedUserName = "ADMIN@BEANSCENE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDxd1Fq7ZI8CN2g3l7pgJKXDN3EiVfeflqEZqvp3dt6AyrWaYMn0+ox2qfNcLwCVfw==",
                            PhoneNumber = "12345678",
                            PhoneNumberConfirmed = false,
                            ProfileUrl = "none",
                            Role = "admin",
                            SecurityStamp = "e9ae5f1b-d63a-457e-8dd7-87790135f9dc",
                            TwoFactorEnabled = false,
                            UserName = "admin@beanscene.com"
                        },
                        new
                        {
                            Id = "da815a98-b0c1-4e33-b2aa-6c0bd7b7ded4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c322422-675b-461d-b0d6-570f63917e5c",
                            Email = "staff@beanscene.com",
                            EmailConfirmed = true,
                            FirstName = "Test",
                            LastName = "Staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF@BEANSCENE.COM",
                            NormalizedUserName = "STAFF@BEANSCENE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDEuZKXJrWVv5EJ7ICAbuifNZWIEp11Z51sVi+eI0b/2LBYv11m23mMcdK/4v3myKg==",
                            PhoneNumber = "12345679",
                            PhoneNumberConfirmed = false,
                            ProfileUrl = "none",
                            Role = "staff",
                            SecurityStamp = "1036a5e2-0675-4627-9b97-131e3d4f8739",
                            TwoFactorEnabled = false,
                            UserName = "staff@beanscene.com"
                        });
                });

            modelBuilder.Entity("BitByByte.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AreaId");

                    b.ToTable("Area");

                    b.HasData(
                        new
                        {
                            AreaId = 1,
                            Description = "The primary dining area with a cozy ambiance.",
                            Name = "Main"
                        },
                        new
                        {
                            AreaId = 2,
                            Description = "A delightful outdoor seating area, surrounded by lush trees.",
                            Name = "Outdoor"
                        },
                        new
                        {
                            AreaId = 3,
                            Description = "An elevated balcony space with a scenic outlook.",
                            Name = "Balcony"
                        });
                });

            modelBuilder.Entity("BitByByte.Models.AssignedTable", b =>
                {
                    b.Property<int>("AssignedTableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignedTableId"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("SittingId")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("AssignedTableId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("SittingId");

                    b.HasIndex("TableId");

                    b.ToTable("AssignedTable");
                });

            modelBuilder.Entity("BitByByte.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationSource")
                        .HasColumnType("int");

                    b.Property<int>("SittingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.HasIndex("SittingId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("BitByByte.Models.Sitting", b =>
                {
                    b.Property<int>("SittingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SittingId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SittingId");

                    b.ToTable("Sitting");
                });

            modelBuilder.Entity("BitByByte.Models.TableInfo", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.HasKey("TableId");

                    b.HasIndex("AreaId");

                    b.ToTable("TableInfo");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 1",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 2,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 2",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 3,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 3",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 4,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 4",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 5,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 5",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 6,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 6",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 7,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 7",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 8,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 8",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 9,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 9",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 10,
                            AreaId = 1,
                            Availability = "Available",
                            Name = "Main 10",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 11,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 1",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 12,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 2",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 13,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 3",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 14,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 4",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 15,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 5",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 16,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 6",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 17,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 7",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 18,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 8",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 19,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 9",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 20,
                            AreaId = 2,
                            Availability = "Available",
                            Name = "Outdoor 10",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 21,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 1",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 22,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 2",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 23,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 3",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 24,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 4",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 25,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 5",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 26,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 6",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 27,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 7",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 28,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 8",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 29,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 9",
                            Seats = 2
                        },
                        new
                        {
                            TableId = 30,
                            AreaId = 3,
                            Availability = "Available",
                            Name = "Balcony 10",
                            Seats = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = "3",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "151d1261-2505-44e4-90fe-3957d31e9a2e",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "da815a98-b0c1-4e33-b2aa-6c0bd7b7ded4",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BitByByte.Models.AssignedTable", b =>
                {
                    b.HasOne("BitByByte.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitByByte.Models.Sitting", "Sitting")
                        .WithMany()
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitByByte.Models.TableInfo", "TableInfo")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Sitting");

                    b.Navigation("TableInfo");
                });

            modelBuilder.Entity("BitByByte.Models.Reservation", b =>
                {
                    b.HasOne("BitByByte.Models.Sitting", "Sitting")
                        .WithMany()
                        .HasForeignKey("SittingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sitting");
                });

            modelBuilder.Entity("BitByByte.Models.TableInfo", b =>
                {
                    b.HasOne("BitByByte.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BitByByte.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BitByByte.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BitByByte.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BitByByte.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
